idf_component_register(
    SRCS
        "main.c"
        "sx_storage_defaults.c"
        "app_task_utils.c"
        "sx_work_mode.c"
        "sx_serial_server.c"
        "sx_serial_port_manager.c"
        "sx_serial_resource.c"
        "sx_led_manager.c"
        "sx_button_manager.c"
        "sx_auto_collect.c"
        "sx_init_wifi.c"
        "sx_time_manager.c"
        "sx_web_server.c"
        "async_uart.c"
        "network/sx_network_manager.c"
        "network/sx_network_config.c"
        "network/modem_manager.c"
        "network/w5500_manager.c"
    EMBED_FILES
        "static/web.html.gz"
        "static/root.html.gz"
        "static/web.js.gz"
        "static/web.css.gz"
    INCLUDE_DIRS
        "."
        "include"
    REQUIRES
        "nvs_flash"
        "esp_netif"
        "esp_event"
        "esp_http_server"
        "esp_wifi"
        "esp_system"
        "esp_timer"
        "driver"
        "freertos"
        "lwip"
        "esp_eth"
        "mqtt"
        "json"
)
