from PySide6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scan_device = QtWidgets.QPushButton(Form)
        self.scan_device.setObjectName("scan_device")
        self.horizontalLayout.addWidget(self.scan_device)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.device_list = QtWidgets.QTableWidget(Form)
        self.device_list.setObjectName("device_list")
        self.device_list.setColumnCount(10)
        self.device_list.setRowCount(0)
        self.device_list.setHorizontalHeaderLabels([
            '设备类型', '设备名称', '操作', '以太网MAC', 'WIFI MAC', 'IP地址',
            '子网掩码', '网关', '版本', '网络类型'
        ])
        self.device_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        header = self.device_list.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.Interactive)
        header.setStretchLastSection(True)
        self.device_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.horizontalLayout_3.addWidget(self.device_list)


        self.update_button = QtWidgets.QPushButton(Form)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout.addWidget(self.update_button)


        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")

        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.et_name = QtWidgets.QLineEdit(Form)
        self.et_name.setObjectName("et_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.et_name)

        self.label_ip_type = QtWidgets.QLabel(Form)
        self.label_ip_type.setObjectName("label_ip_type")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_ip_type)
        self.ip_type_layout = QtWidgets.QHBoxLayout()
        self.ip_type_layout.setObjectName("ip_type_layout")
        self.rb_static_ip = QtWidgets.QRadioButton(Form)
        self.rb_static_ip.setObjectName("rb_static_ip")
        self.ip_type_layout.addWidget(self.rb_static_ip)
        self.rb_dhcp_ip = QtWidgets.QRadioButton(Form)
        self.rb_dhcp_ip.setObjectName("rb_dhcp_ip")
        self.ip_type_layout.addWidget(self.rb_dhcp_ip)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.ip_type_layout)

        self.label_ip = QtWidgets.QLabel(Form)
        self.label_ip.setObjectName("label_ip")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_ip)
        self.et_ip = QtWidgets.QLineEdit(Form)
        self.et_ip.setObjectName("et_ip")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.et_ip)

        self.label_mask = QtWidgets.QLabel(Form)
        self.label_mask.setObjectName("label_mask")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_mask)
        self.et_mask = QtWidgets.QLineEdit(Form)
        self.et_mask.setObjectName("et_mask")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.et_mask)

        self.label_gateway = QtWidgets.QLabel(Form)
        self.label_gateway.setObjectName("label_gateway")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_gateway)
        self.et_gateway = QtWidgets.QLineEdit(Form)
        self.et_gateway.setObjectName("et_gateway")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.et_gateway)

        self.label_primary_dns = QtWidgets.QLabel(Form)
        self.label_primary_dns.setObjectName("label_primary_dns")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_primary_dns)
        self.et_primary_dns = QtWidgets.QLineEdit(Form)
        self.et_primary_dns.setObjectName("et_primary_dns")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.et_primary_dns)

        self.label_secondary_dns = QtWidgets.QLabel(Form)
        self.label_secondary_dns.setObjectName("label_secondary_dns")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_secondary_dns)
        self.et_secondary_dns = QtWidgets.QLineEdit(Form)
        self.et_secondary_dns.setObjectName("et_secondary_dns")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.et_secondary_dns)

        self.reset_ip = QtWidgets.QPushButton(Form)
        self.reset_ip.setObjectName("reset_ip")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.reset_ip)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_cmd = QtWidgets.QLabel(Form)
        self.label_cmd.setObjectName("label_cmd")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_cmd)
        self.et_remote_cmd = QtWidgets.QLineEdit(Form)
        self.et_remote_cmd.setObjectName("et_remote_cmd")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.et_remote_cmd)
        self.exec_remote_cmd = QtWidgets.QPushButton(Form)
        self.exec_remote_cmd.setObjectName("exec_remote_cmd")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.exec_remote_cmd)
        self.et_cmd_result = QtWidgets.QTextEdit(Form)
        self.et_cmd_result.setObjectName("et_cmd_result")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.et_cmd_result)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_taobao = QtWidgets.QLabel(Form)
        self.label_taobao.setObjectName("label_taobao")
        self.label_taobao.setText('<a href="https://www.likong-iot.com">立控官网</a>')
        self.label_taobao.setOpenExternalLinks(True)
        self.horizontalLayout_4.addWidget(self.label_taobao)
        self.label_baidu = QtWidgets.QLabel(Form)
        self.label_baidu.setObjectName("label_baidu")
        self.label_baidu.setText('<a href="https://likongdianzi.taobao.com/">产品购买</a>')
        self.label_baidu.setOpenExternalLinks(True)
        self.horizontalLayout_4.addWidget(self.label_baidu)

        self.label_web_debug = QtWidgets.QLabel(Form)
        self.label_web_debug.setObjectName("label_web_debug")
        self.label_web_debug.setText('<a href="https://debug.likong-iot.com">Web调试</a>')
        self.label_web_debug.setOpenExternalLinks(True)
        self.label_web_debug.setStyleSheet("QLabel { text-decoration: none; }")
        self.horizontalLayout_4.addWidget(self.label_web_debug)

        self.label_doc = QtWidgets.QLabel(Form)
        self.label_doc.setObjectName("label_doc")
        self.label_doc.setText('<a href="https://docv2.likong-iot.com">接入文档</a>')
        self.label_doc.setOpenExternalLinks(True)
        self.label_doc.setStyleSheet("QLabel { text-decoration: none; }")
        self.horizontalLayout_4.addWidget(self.label_doc)


        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.scan_device.setText(_translate("Form", "搜索设备"))
        self.update_button.setText(_translate("Form", "在线升级"))
        self.label_name.setText(_translate("Form", "设备名称:"))
        self.label_ip_type.setText(_translate("Form", "网络类型:"))
        self.rb_static_ip.setText(_translate("Form", "静态IP"))
        self.rb_dhcp_ip.setText(_translate("Form", "动态IP"))
        self.label_ip.setText(_translate("Form", "IP地址:"))
        self.label_mask.setText(_translate("Form", "子网掩码:"))
        self.label_gateway.setText(_translate("Form", "网关地址:"))
        self.label_primary_dns.setText(_translate("Form", "主DNS:"))
        self.label_secondary_dns.setText(_translate("Form", "备用DNS:"))
        self.reset_ip.setText(_translate("Form", "重新设置"))
        self.label_cmd.setText(_translate("Form", "远程命令:"))
        self.exec_remote_cmd.setText(_translate("Form", "执行远程命令"))
